name: jeremy.odell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0168cd'
    - '#e23137'
    - '#fefdfe'
    - '#8ba1bf'
    - '#d29697'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
