name: jeremy.odell
favicon: null
layout_spectrum: 0.2500810471829027
typography_spectrum: 0.08719440153799951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08144690911285579
  lightness: 0.31791510386392474
  saturation: 0.7884539549704641
  rhythmicContrast: 0.8796900568995625
purpose: []
